language: node_js
node_js:
  - "10.7.0"
  - "node"
cache: - yarn

directories:
  - node_modules

install: 
  -yarn install

script:
  - npm test
  -yarn run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $JWT_KEY
  local_dir: build
  on:
    branch: master